import { User } from '@/types/user';
import { Workspace } from '@/types/workspace';
import { Project, ProjectTemplate } from '@/types/project';
import { Task, KanbanColumn } from '@/types/task';
import { Comment } from '@/types/comment';
import { ActivityEvent } from '@/types/activity';
import { AppNotification } from '@/types/notification';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@acme.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'owner',
    title: 'Lead Architect & Founder',
  },
  {
    id: 'user-2',
    name: 'Sarah Chen',
    email: 'sarah.chen@acme.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    title: 'Staff Product Designer',
  },
  {
    id: 'user-3',
    name: 'Michael Scott',
    email: 'michael.scott@acme.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    title: 'Senior Frontend Engineer',
  },
  {
    id: 'user-4',
    name: 'Emma Watson',
    email: 'emma.watson@acme.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'viewer',
    title: 'External Stakeholder & Auditor',
  },
  {
    id: 'user-5',
    name: 'David Kim',
    email: 'david.kim@acme.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    title: 'DevOps & Site Reliability Engineer',
  },
];

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-1',
    name: 'Acme Engineering',
    icon: '🚀',
    color: '#6366f1',
    defaultView: 'kanban',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerId: 'user-1',
    members: [
      { userId: 'user-1', role: 'owner', joinedAt: new Date(Date.now() - 30 * 86400000).toISOString() },
      { userId: 'user-2', role: 'admin', joinedAt: new Date(Date.now() - 25 * 86400000).toISOString() },
      { userId: 'user-3', role: 'member', joinedAt: new Date(Date.now() - 20 * 86400000).toISOString() },
      { userId: 'user-4', role: 'viewer', joinedAt: new Date(Date.now() - 15 * 86400000).toISOString() },
      { userId: 'user-5', role: 'member', joinedAt: new Date(Date.now() - 10 * 86400000).toISOString() },
    ],
  },
  {
    id: 'ws-2',
    name: 'Global Marketing',
    icon: '📈',
    color: '#ec4899',
    defaultView: 'list',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerId: 'user-1',
    members: [
      { userId: 'user-1', role: 'owner', joinedAt: new Date(Date.now() - 14 * 86400000).toISOString() },
      { userId: 'user-2', role: 'admin', joinedAt: new Date(Date.now() - 12 * 86400000).toISOString() },
      { userId: 'user-3', role: 'member', joinedAt: new Date(Date.now() - 10 * 86400000).toISOString() },
    ],
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    workspaceId: 'ws-1',
    name: 'NextGen SaaS Platform',
    description: 'Core multi-tenant cloud workspace infrastructure, APIs, and modern client applications.',
    icon: '⚡',
    color: '#6366f1',
    isArchived: false,
    memberIds: ['user-1', 'user-2', 'user-3', 'user-5'],
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    workspaceId: 'ws-1',
    name: 'Mobile Client Experience',
    description: 'iOS and Android companion applications with offline capability and biometric unlock.',
    icon: '📱',
    color: '#10b981',
    isArchived: false,
    memberIds: ['user-2', 'user-3'],
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    workspaceId: 'ws-1',
    name: 'Security & Compliance Audits',
    description: 'SOC2 Type II certification preparation, RBAC validation, and cryptographic audit log storage.',
    icon: '🛡️',
    color: '#f59e0b',
    isArchived: false,
    memberIds: ['user-1', 'user-4', 'user-5'],
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-4',
    workspaceId: 'ws-1',
    name: 'Legacy Monolith Deprecation',
    description: 'Decommissioning old PHP/MySQL services and migrating remaining endpoints.',
    icon: '📦',
    color: '#64748b',
    isArchived: true,
    memberIds: ['user-1', 'user-5'],
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-5',
    workspaceId: 'ws-2',
    name: 'Q3 Product Launch Campaign',
    description: 'Multi-channel marketing initiative including Product Hunt, press outreach, and video collateral.',
    icon: '🎯',
    color: '#ec4899',
    isArchived: false,
    memberIds: ['user-1', 'user-2', 'user-3'],
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_COLUMNS: Record<string, KanbanColumn[]> = {
  'proj-1': [
    { id: 'col-1-1', projectId: 'proj-1', name: 'Backlog', color: '#94a3b8', order: 0 },
    { id: 'col-1-2', projectId: 'proj-1', name: 'In Progress', color: '#3b82f6', order: 1 },
    { id: 'col-1-3', projectId: 'proj-1', name: 'In Review', color: '#a855f7', order: 2 },
    { id: 'col-1-4', projectId: 'proj-1', name: 'Done', color: '#10b981', order: 3 },
  ],
  'proj-2': [
    { id: 'col-2-1', projectId: 'proj-2', name: 'Todo', color: '#94a3b8', order: 0 },
    { id: 'col-2-2', projectId: 'proj-2', name: 'Designing', color: '#ec4899', order: 1 },
    { id: 'col-2-3', projectId: 'proj-2', name: 'Developing', color: '#3b82f6', order: 2 },
    { id: 'col-2-4', projectId: 'proj-2', name: 'Shipped', color: '#10b981', order: 3 },
  ],
  'proj-3': [
    { id: 'col-3-1', projectId: 'proj-3', name: 'Identified', color: '#94a3b8', order: 0 },
    { id: 'col-3-2', projectId: 'proj-3', name: 'Auditing', color: '#f59e0b', order: 1 },
    { id: 'col-3-3', projectId: 'proj-3', name: 'Resolved', color: '#10b981', order: 2 },
  ],
  'proj-5': [
    { id: 'col-5-1', projectId: 'proj-5', name: 'Ideation', color: '#94a3b8', order: 0 },
    { id: 'col-5-2', projectId: 'proj-5', name: 'In Production', color: '#3b82f6', order: 1 },
    { id: 'col-5-3', projectId: 'proj-5', name: 'Published', color: '#10b981', order: 2 },
  ],
};

export const INITIAL_TASKS: Record<string, Task> = {
  'task-1': {
    id: 'task-1',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Implement OAuth2 & Multi-Factor Auth Flow',
    description: 'Build enterprise-grade authentication with WebAuthn, TOTP, and single sign-on support. Ensure tokens rotate safely.',
    status: 'In Progress',
    priority: 'urgent',
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-3',
    labels: ['Security', 'Auth', 'Backend'],
    subtasks: [
      {
        id: 'sub-1',
        parentId: null,
        title: 'Draft RFC for token refresh rotation',
        completed: true,
        children: [
          { id: 'sub-1-1', parentId: 'sub-1', title: 'Review RFC with Security team', completed: true },
        ],
      },
      {
        id: 'sub-2',
        parentId: null,
        title: 'Implement PKCE flow for mobile & desktop clients',
        completed: true,
      },
      {
        id: 'sub-3',
        parentId: null,
        title: 'Build UI for QR-code 2FA authenticator setup',
        completed: false,
        children: [
          { id: 'sub-3-1', parentId: 'sub-3', title: 'Add backup recovery codes generator', completed: false },
        ],
      },
    ],
    attachments: [
      {
        id: 'att-1',
        taskId: 'task-1',
        name: 'oauth2-architecture-spec.pdf',
        size: 245000,
        type: 'application/pdf',
        dataUrl: 'data:application/pdf;base64,JVBERi0xLjUKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCg==',
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  'task-2': {
    id: 'task-2',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Design High-Density Kanban Board Interaction',
    description: 'Refine micro-interactions for dragging cards across columns, drop indicators, column reordering, and keyboard accessibility.',
    status: 'In Review',
    priority: 'high',
    dueDate: new Date(Date.now() + 1 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-2',
    labels: ['Design', 'UI/UX', 'Components'],
    subtasks: [
      { id: 'sub-4', parentId: null, title: 'Card hover elevation and priority badges', completed: true },
      { id: 'sub-5', parentId: null, title: 'Drag handle and preview ghost styling', completed: true },
      { id: 'sub-6', parentId: null, title: 'Accessibility focus indicators and arrow key reordering', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'task-3': {
    id: 'task-3',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Optimize IndexedDB Sync Engine for Offline Mode',
    description: 'Ensure queued actions serialize cleanly when browser is offline, and trigger optimistic reconciliation on network reconnection.',
    status: 'Backlog',
    priority: 'high',
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-1',
    labels: ['Storage', 'Performance', 'Offline'],
    subtasks: [
      { id: 'sub-7', parentId: null, title: 'Benchmark serialization latency for 1,000 tasks', completed: true },
      { id: 'sub-8', parentId: null, title: 'Build conflict resolution handler', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'task-4': {
    id: 'task-4',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Set up Automated End-to-End Test Suite',
    description: 'Add Playwright/Cypress end-to-end coverage across authentication, workspace creation, and task management pipelines.',
    status: 'Done',
    priority: 'medium',
    dueDate: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-5',
    labels: ['Testing', 'DevOps', 'CI/CD'],
    subtasks: [
      { id: 'sub-9', parentId: null, title: 'Configure CI runner on GitHub Actions', completed: true },
      { id: 'sub-10', parentId: null, title: 'Add test coverage matrix for Chrome, Firefox, WebKit', completed: true },
    ],
    attachments: [],
    order: 0,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  'task-5': {
    id: 'task-5',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Revamp Dark Theme Tokens & Elevation Hierarchy',
    description: 'Refine contrast ratios, border subtlety, and dark mode background depth according to WCAG 2.1 AA standards.',
    status: 'Done',
    priority: 'medium',
    dueDate: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-2',
    labels: ['Design', 'Theme', 'A11y'],
    subtasks: [
      { id: 'sub-11', parentId: null, title: 'Verify contrast on muted text against card backgrounds', completed: true },
    ],
    attachments: [],
    order: 1,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  'task-6': {
    id: 'task-6',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Refactor Subtask Tree to Support Arbitrary Nesting',
    description: 'Enable checklist subtasks to have parent-child hierarchies with cascading completion and subtask-to-task promotion.',
    status: 'In Progress',
    priority: 'urgent',
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-1',
    labels: ['Architecture', 'Frontend'],
    subtasks: [
      { id: 'sub-12', parentId: null, title: 'Write recursive tree renderer component', completed: true },
      { id: 'sub-13', parentId: null, title: 'Add depth-indent visual indicators', completed: false },
    ],
    attachments: [],
    order: 1,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'task-7': {
    id: 'task-7',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Implement Role-Based Access Control Gateways',
    description: 'Enforce granular permissions for Owner, Admin, Member, and Viewer with client-side guards and access-denied state dialogs.',
    status: 'Backlog',
    priority: 'high',
    dueDate: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-3',
    labels: ['Security', 'RBAC', 'Architecture'],
    subtasks: [
      { id: 'sub-14', parentId: null, title: 'Define central permission matrix helper', completed: true },
      { id: 'sub-15', parentId: null, title: 'Design professional Access Restricted modal', completed: false },
    ],
    attachments: [],
    order: 1,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'task-8': {
    id: 'task-8',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    title: 'Mobile Drawer Navigation & Touch Gestures',
    description: 'Optimize collapsible sidebar drawer for smartphone viewports and horizontal swipe for Kanban columns.',
    status: 'Backlog',
    priority: 'low',
    dueDate: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-2',
    labels: ['Mobile', 'Responsive', 'UX'],
    subtasks: [
      { id: 'sub-16', parentId: null, title: 'Test touch target sizes (minimum 44x44px)', completed: false },
    ],
    attachments: [],
    order: 2,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'task-9': {
    id: 'task-9',
    projectId: 'proj-2',
    workspaceId: 'ws-1',
    title: 'Biometric FaceID / TouchID Unlock Hook',
    description: 'Integrate WebAuthn biometric credentials for rapid mobile re-authentication.',
    status: 'Designing',
    priority: 'medium',
    dueDate: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-3',
    labels: ['Mobile', 'Security'],
    subtasks: [],
    attachments: [],
    order: 0,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'task-10': {
    id: 'task-10',
    projectId: 'proj-5',
    workspaceId: 'ws-2',
    title: 'Produce 60-second Product Walkthrough Video',
    description: 'Record high-resolution UI screen capture showcasing Kanban, command palette, and collaboration features.',
    status: 'In Production',
    priority: 'high',
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    assigneeId: 'user-2',
    labels: ['Marketing', 'Video', 'Launch'],
    subtasks: [
      { id: 'sub-17', parentId: null, title: 'Script key talking points and product flows', completed: true },
      { id: 'sub-18', parentId: null, title: 'Record voiceover track', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
};

export const INITIAL_COMMENTS: Record<string, Comment[]> = {
  'task-1': [
    {
      id: 'comm-1',
      taskId: 'task-1',
      authorId: 'user-1',
      content: 'Make sure we include WebAuthn credentials in the RFC before finalizing the backend contract. @Sarah Chen please review the UX flow when you get a chance!',
      mentions: ['user-2'],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'comm-2',
      taskId: 'task-1',
      authorId: 'user-2',
      content: 'Reviewed! The authenticator backup flow looks intuitive. Added Figma comments for the QR code scanning card.',
      mentions: [],
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ],
  'task-2': [
    {
      id: 'comm-3',
      taskId: 'task-2',
      authorId: 'user-3',
      content: 'The drag-and-drop animation feels incredibly fluid! Tested reordering within columns and dropping between status lanes.',
      mentions: [],
      createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    },
  ],
};

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-1',
    taskId: 'task-2',
    taskTitle: 'Design High-Density Kanban Board Interaction',
    projectId: 'proj-1',
    projectName: 'NextGen SaaS Platform',
    workspaceId: 'ws-1',
    actorId: 'user-2',
    actionType: 'status_changed',
    details: 'moved task from In Progress to In Review',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'act-2',
    taskId: 'task-1',
    taskTitle: 'Implement OAuth2 & Multi-Factor Auth Flow',
    projectId: 'proj-1',
    projectName: 'NextGen SaaS Platform',
    workspaceId: 'ws-1',
    actorId: 'user-3',
    actionType: 'subtask_toggled',
    details: 'completed subtask "Draft RFC for token refresh rotation"',
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'act-3',
    taskId: 'task-1',
    taskTitle: 'Implement OAuth2 & Multi-Factor Auth Flow',
    projectId: 'proj-1',
    projectName: 'NextGen SaaS Platform',
    workspaceId: 'ws-1',
    actorId: 'user-1',
    actionType: 'comment_added',
    details: 'commented on task',
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'act-4',
    taskId: 'task-4',
    taskTitle: 'Set up Automated End-to-End Test Suite',
    projectId: 'proj-1',
    projectName: 'NextGen SaaS Platform',
    workspaceId: 'ws-1',
    actorId: 'user-5',
    actionType: 'status_changed',
    details: 'marked task as Done',
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'act-5',
    projectId: 'proj-1',
    projectName: 'NextGen SaaS Platform',
    workspaceId: 'ws-1',
    actorId: 'user-1',
    actionType: 'project_created',
    details: 'created project "NextGen SaaS Platform"',
    timestamp: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: 'Task Assigned',
    message: 'Sarah Chen assigned you to "Optimize IndexedDB Sync Engine for Offline Mode"',
    type: 'assignment',
    taskId: 'task-3',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    read: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: 'Mention in Comment',
    message: 'Sarah Chen mentioned you in "Implement OAuth2 & Multi-Factor Auth Flow"',
    type: 'mention',
    taskId: 'task-1',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    read: false,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    title: 'Upcoming Deadline',
    message: '"Implement OAuth2 & Multi-Factor Auth Flow" is due in 2 days',
    type: 'due_date',
    taskId: 'task-1',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    read: true,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'tmpl-software',
    name: 'Software Development',
    description: 'Agile sprint-ready project setup with backlog, development, review, and deployment pipelines.',
    icon: '💻',
    color: '#6366f1',
    columns: ['Backlog', 'In Progress', 'In Review', 'Done'],
    initialTasks: [
      {
        title: 'Sprint Planning & Architecture Alignment',
        description: 'Define key deliverables, architecture diagrams, and milestones for the upcoming sprint cycle.',
        priority: 'high',
        statusColumnName: 'Backlog',
        labels: ['Planning', 'Architecture'],
        subtasks: ['Review technical prerequisites', 'Estimate story points', 'Assign sprint roles'],
      },
      {
        title: 'Core API Specification & Schema Validation',
        description: 'Design OpenAPI v3 specifications, input schemas, and error contract responses.',
        priority: 'urgent',
        statusColumnName: 'In Progress',
        labels: ['Backend', 'API'],
        subtasks: ['Write schema types', 'Configure validation middleware'],
      },
      {
        title: 'Automated CI/CD Deployment Pipeline',
        description: 'Configure automated pull request checks, unit tests, and preview deployment environments.',
        priority: 'medium',
        statusColumnName: 'In Review',
        labels: ['DevOps', 'CI/CD'],
      },
      {
        title: 'Repository Setup & ESLint / Prettier Config',
        description: 'Bootstrap codebase with strict TypeScript rules, path aliases, and git hygiene hooks.',
        priority: 'low',
        statusColumnName: 'Done',
        labels: ['Setup', 'Tooling'],
      },
    ],
  },
  {
    id: 'tmpl-marketing',
    name: 'Marketing Campaign',
    description: 'Comprehensive campaign tracker from content creation to influencer outreach and conversion analytics.',
    icon: '📣',
    color: '#ec4899',
    columns: ['Content Strategy', 'Drafting', 'Design Review', 'Published'],
    initialTasks: [
      {
        title: 'Target Audience Persona & Messaging Framework',
        description: 'Define core user personas, value propositions, and pain-point messaging matrix.',
        priority: 'high',
        statusColumnName: 'Content Strategy',
        labels: ['Strategy', 'Research'],
      },
      {
        title: 'Hero Landing Page Copy & Visual Assets',
        description: 'Draft punchy headlines, testimonials, feature callouts, and 3D illustration renders.',
        priority: 'urgent',
        statusColumnName: 'Drafting',
        labels: ['Copywriting', 'Design'],
      },
      {
        title: 'Multi-channel Email Sequence & Automation',
        description: 'Setup welcome drip campaign, onboarding checklists, and trigger-based notifications.',
        priority: 'medium',
        statusColumnName: 'Design Review',
        labels: ['Email', 'Automation'],
      },
    ],
  },
  {
    id: 'tmpl-product-launch',
    name: 'Product Launch',
    description: 'End-to-end launch plan covering PRD review, beta user feedback, press kit, and post-launch retro.',
    icon: '🚀',
    color: '#f59e0b',
    columns: ['Pre-Launch', 'Beta Testing', 'Launch Day', 'Post-Launch'],
    initialTasks: [
      {
        title: 'Press Kit & High-Resolution Asset Bundle',
        description: 'Assemble company logo pack, product screenshots, founder bios, and press release draft.',
        priority: 'high',
        statusColumnName: 'Pre-Launch',
        labels: ['PR', 'Media'],
      },
      {
        title: 'Private Beta Cohort Feedback Synthesis',
        description: 'Collate user interview takeaways, bugs reported by beta testers, and NPS scores.',
        priority: 'urgent',
        statusColumnName: 'Beta Testing',
        labels: ['Feedback', 'UX'],
      },
      {
        title: 'Product Hunt & Social Media Blitz Plan',
        description: 'Schedule maker comment, hunter outreach, teaser tweets, and community AMA.',
        priority: 'high',
        statusColumnName: 'Pre-Launch',
        labels: ['Community', 'Launch'],
      },
    ],
  },
  {
    id: 'tmpl-personal',
    name: 'Personal Productivity',
    description: 'Structured goal planning, daily habits, deep work blocks, and reflective weekly reviews.',
    icon: '🌱',
    color: '#10b981',
    columns: ['To Do', 'Today', 'Deep Work', 'Accomplished'],
    initialTasks: [
      {
        title: 'Quarterly Objectives & Key Results (OKRs)',
        description: 'Establish 3 personal growth milestones with measurable key results and weekly check-ins.',
        priority: 'high',
        statusColumnName: 'To Do',
        labels: ['Goals', 'Reflection'],
      },
      {
        title: 'Clean Desktop & Archive Stale Downloads',
        description: 'Declutter workspace, organize cloud storage, and backup critical local documents.',
        priority: 'low',
        statusColumnName: 'Today',
        labels: ['Organization'],
      },
    ],
  },
];
